import type {Alert} from './main';
const descriptions:Record<string,string>={pps:'Packets per second in the 2-second observation window',bps:'Observed bytes per second',syn_fraction:'Fraction of observed packets carrying SYN',unique_ports:'Distinct TCP destination ports receiving SYN probes over the last 10 seconds',mean_size:'Average observed packet size in bytes',size_std:'Variation in packet size, in bytes',dns_entropy:'Maximum first-label DNS character entropy',dns_length:'Longest first DNS label, in characters',dns_txt_fraction:'Fraction of DNS queries requesting TXT records',beacon_cv:'Variation divided by mean connection-start interval',beacon_count:'Retained connection starts used for timing analysis',ja4_watchlist:'Observed fingerprint matched the local watchlist'};
const human=(s:string)=>s.replaceAll('_',' ');
export function ShapPanel({alert:a}:{alert:Alert}){
 const x=a.shap_explanation;const score=x?.model_score??a.model_vote?.confidence;
 const mismatch=!!a.shap_explains_class&&a.shap_explains_class!==a.threat_class;
 const largest=Math.max(.00001,...a.shap.map(f=>Math.abs(f.contribution)));
 const points=(n:number)=>(n>=0?'+':'')+(n*100).toFixed(2)+' pp';
 return <section className="shap-panel"><h3>Why the model voted this way</h3><p>Explained class: <strong>{human(a.shap_explains_class??'unavailable')}</strong>{score!=null?` · ${(score*100).toFixed(1)}% model vote`:''}</p>
 {mismatch&&<div className="shap-disagreement"><strong>Model and behavioral alert differ</strong><p>The alert is {human(a.threat_class)}. These bars explain the model’s {human(a.shap_explains_class)} vote. Read the observed evidence above for the alert’s reason.</p></div>}
 {a.threat_class==='unknown_anomaly'&&a.model_vote?.isolation_score!=null&&<div className="anomaly-reason"><strong>Actual anomaly trigger: IsolationForest</strong><p>Anomaly score {a.model_vote.isolation_score.toFixed(4)} exceeded baseline threshold {a.model_vote.isolation_threshold?.toFixed(4)??'unavailable'}. The SHAP bars below explain the separate classifier vote, not this anomaly score.</p></div>}
 {!a.shap.length?<p>SHAP explanation is unavailable for this record.</p>:<><div className="shap-legend"><span>← lowers this class score</span><span>raises this class score →</span></div>{a.shap.map(f=><div className="shap-feature" key={f.feature}><div><strong>{human(f.feature)}</strong><b className={f.contribution>=0?'shap-positive':'shap-negative'}>{points(f.contribution)}</b></div><p>{descriptions[f.feature]??human(f.feature)} · value {Number(f.value.toFixed(3))}</p><div className="shap-track"><i style={{left:f.contribution>=0?'50%':`${50-48*Math.abs(f.contribution)/largest}%`,width:`${Math.max(.4,48*Math.abs(f.contribution)/largest)}%`,background:f.contribution>=0?'var(--lavender)':'var(--blue)'}}/></div></div>)}{x?.available&&<><div className="shap-equation"><span>Baseline<strong>{(x.base_value*100).toFixed(2)}%</strong></span><span>All feature effects<strong>{points(x.contribution_sum)}</strong></span><span>Model vote<strong>{(x.model_score*100).toFixed(2)}%</strong></span></div><p className="footnote">Other features combined: {points(x.other_contribution)}. {x.additivity_verified?'Baseline + contributions matches the model score.':'Explanation reconstruction was not verified.'}</p></>}</>}
 <p className="footnote">SHAP explains the classifier’s output; its training scope is shown on the System page. It does not establish causation or a calibrated probability of an attack. “pp” means percentage points.</p></section>
}
