import {useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Shield,Activity,Network,Radio,Play,Pause,Download,ChevronRight,ChevronLeft,Layers,Eye,Sun,Moon,Search,X,ArrowUpRight,Globe,Focus,ArrowRight} from 'lucide-react';
import '@xyflow/react/dist/style.css';
import './style.css';
import {TrafficGraph} from './TrafficGraph';
import {ShapPanel} from './ShapPanel';
import {PassiveIllustration,SecurityIllustration} from './PassiveIllustration';
export type Theme='light'|'dark';type Tab='packets'|'detections'|'graph'|'system';
export type Alert={id:string;timestamp:number;src:string;dst:string;related_sources?:string[];threat_class:string;severity:string;confidence:number|null;confidence_type:string;source:string;evidence:string[];features:Record<string,number>;shap:{feature:string;contribution:number;value:number}[];shap_explains_class:string;model_vote?:{confidence:number|null;label:string|null;kitnet_error?:number|null;kitnet_threshold?:number|null};shap_explanation?:{available:boolean;class:string;base_value:number;model_score:number;contribution_sum:number;other_contribution:number;additivity_verified:boolean;reconstruction_error:number};ja4:string[];dns_samples:string[]};
type Packet={sequence:number;timestamp:number;src:string;dst:string;sport:number;dport:number;protocol:string;length:number;uid:string;tcp_flags:number|null;syn:boolean;source:string;scope:string;ip_version:number;prefix:string};
type Page={items:Packet[];next_before:number|null;retained:number;capacity:number;total_captured:number;oldest_sequence:number|null;newest_sequence:number;expired:number};
export type Host={id:string;scope:string;ip_version:number;prefix:string;roles:string[];alert_ids:string[];packets:number;bytes:number;last_seen:number;peers:string[];recent:boolean};
export type Edge={id:string;source:string;target:string;packets:number;bytes:number;first:number|null;last:number;recent:boolean;alert_ids:string[];suspicious:boolean;ports?:{protocol:string;port:number;packets:number}[];ports_truncated?:boolean};
export type Graph={nodes:Host[];edges:Edge[];recent_seconds:number;linked_alerts:number;capacity:number;capacity_drops:number;scope:string};
type State={status:{mode:string;last_event:number|null;last_error:string|null};metrics:Record<string,number>;alerts:Alert[];models:Record<string,string>;capabilities:Record<string,string>;packets:Page|null;graph:Graph|null};
let csrf='';
async function api(url:string,options:RequestInit={}){const response=await fetch(url,{...options,headers:{...options.headers,...(options.method&&options.method!=='GET'?{'X-CSRF-Token':csrf}:{})}});if(response.status===401)window.dispatchEvent(new Event('veil-signout'));return response}
const EMPTY:Page={items:[],next_before:null,retained:0,capacity:10000,total_captured:0,oldest_sequence:null,newest_sequence:0,expired:0};
const pretty=(s:string)=>s.replaceAll('_',' ');
const clock=(t:number,ms=false)=>new Date(t*1000).toLocaleTimeString([],ms?{hour12:false,hour:'2-digit',minute:'2-digit',second:'2-digit',fractionalSecondDigits:3}:{hour12:false});
const count=(n:number|undefined)=>(n??0).toLocaleString();
const bytes=(n:number)=>n>=1e6?`${(n/1e6).toFixed(1)} MB`:n>=1000?`${(n/1000).toFixed(1)} kB`:`${n} B`;
const scopeName=(s:string)=>s==='documentation'?'Demo address':s==='public'?'Public IP':s==='private'?'Private IP':pretty(s);
function Empty({title,detail}:{title:string;detail:string}){return <div className="empty"><Radio size={30}/><h3>{title}</h3><p>{detail}</p></div>}

function PacketPage({state,open}:{state:State|null;open:(p:Packet)=>void}){
 const [query,setQuery]=useState(''),[scope,setScope]=useState('all'),[before,setBefore]=useState<number|null>(null),[history,setHistory]=useState<(number|null)[]>([]),[remote,setRemote]=useState<Page|null>(null),[frozen,setFrozen]=useState<Page|null>(null),[error,setError]=useState('');
 const custom=!!query||scope!=='all'||before!==null;
 useEffect(()=>{if(!custom)return;let stopped=false;let controller:AbortController|undefined;const load=async()=>{controller=new AbortController();const p=new URLSearchParams({q:query,scope,limit:'100'});if(before!==null)p.set('before',String(before));try{let r=await api('/api/packets?'+p,{signal:controller.signal});if(!r.ok)throw Error('Packet list unavailable');let data=await r.json();if(!stopped){setRemote(data);setError('')}}catch(e){if(!stopped&&(e as Error).name!=='AbortError')setError('Packet list unavailable. Reconnect to the backend.')}};setRemote(null);void load();const timer=before===null&&!frozen?setInterval(load,500):undefined;return()=>{stopped=true;controller?.abort();if(timer)clearInterval(timer)}},[query,scope,before,!!frozen,custom]);
 const page=frozen??(custom?remote:state?.packets)??EMPTY;
 const reset=()=>{setBefore(null);setHistory([]);setFrozen(null)};
 const filter=(q:string,s:string)=>{setQuery(q);setScope(s);reset()};
 const older=()=>{if(page.next_before){setFrozen(null);setHistory([...history,before]);setBefore(page.next_before)}};
 const newer=()=>{setFrozen(null);const h=[...history];setBefore(h.pop()??null);setHistory(h)};
 return <><div className="section-intro"><div><h2>Captured packets <span className="pill">{count(state?.metrics.packets)} total</span></h2><p>Every source network visible at the mirror. Packet headers and metadata only.</p></div><a className="button secondary" href="/api/packets/export"><Download size={17}/>Export recent packets</a></div>
 <PassiveIllustration/><div className="packet-summary"><div><Radio size={20}/><span>Packets captured<strong>{count(state?.metrics.packets)}</strong></span></div><div><Activity size={20}/><span>Bytes observed<strong>{bytes(state?.metrics.captured_bytes??0)}</strong></span></div><div><Globe size={20}/><span>Source visibility<strong>All observed networks</strong></span></div><div><span className={'status-dot '+(frozen||before!==null?'muted-dot':'')}/><span>Display updates<strong>{frozen||before!==null?'Paused for browsing':'Every 500 ms'}</strong></span></div></div>
 <section className="panel"><div className="table-toolbar"><label className="search"><Search size={18}/><input aria-label="Search packets" placeholder="Search IP, port or protocol" value={query} onChange={e=>filter(e.target.value,scope)}/></label><select aria-label="Filter source address scope" value={scope} onChange={e=>filter(query,e.target.value)}><option value="all">All address scopes</option><option value="public">Public IPs</option><option value="private">Private IPs</option><option value="documentation">Demo addresses</option><option value="link-local">Link-local</option><option value="loopback">Loopback</option><option value="reserved">Reserved</option></select><button className="button secondary" onClick={()=>frozen||before!==null?reset():setFrozen(page)}>{frozen||before!==null?<Play size={16}/>:<Pause size={16}/>} {frozen||before!==null?'Resume latest':'Pause view'}</button></div>
 {error&&<div role="alert" className="inline-note danger-text">{error}</div>}<div className="packet-table table-scroll"><table><thead><tr><th>Sequence / time</th><th>Source</th><th>Destination</th><th>Protocol</th><th>Size</th><th>Address scope</th><th/></tr></thead><tbody>{page.items.map(p=><tr key={p.sequence} onClick={()=>open(p)}><td><span className="mono">#{p.sequence}</span><small>{clock(p.timestamp,true)}</small></td><td><strong className="mono">{p.src}</strong><small>Port {p.sport||'—'}</small></td><td><strong className="mono">{p.dst}</strong><small>Port {p.dport||'—'}</small></td><td><span className="protocol">{p.protocol.toUpperCase()}</span></td><td className="mono">{p.length} B</td><td><span className="scope-tag">{scopeName(p.scope)}</span><small>IPv{p.ip_version} · {p.source}</small></td><td><button className="icon-button" aria-label={`Inspect packet ${p.sequence}`}><ArrowUpRight size={17}/></button></td></tr>)}</tbody></table>{!page.items.length&&<Empty title={query||scope!=='all'?'No matching packets':'Waiting for mirrored packets'} detail={query||scope!=='all'?'Change your search or address filter.':'Start the demo replay or connect the live Zeek stream.'}/>}</div>
 <div className="table-footer"><span>{page.items.length?`Showing #${page.items[0].sequence}–#${page.items.at(-1)!.sequence}`:'No packets yet'} · {count(page.retained)} retained</span><div><button className="button secondary" disabled={!history.length} onClick={newer}><ChevronLeft size={17}/>Newer</button><button className="button secondary" disabled={!page.next_before} onClick={older}>Older<ChevronRight size={17}/></button></div></div></section>
 <p className="footnote">Browse the latest {count(page.capacity)} packet records here; older rows expire from this buffer. The capture host keeps the full Zeek metadata log. No source subnet is excluded by the dashboard.</p></>
}
function DetectionPage({alerts,open,graph}:{alerts:Alert[];open:(a:Alert)=>void;graph:(a:Alert)=>void}){
 const [query,setQuery]=useState('');const rows=alerts.filter(a=>`${a.src} ${a.dst} ${a.threat_class} ${a.severity} ${a.id}`.toLowerCase().includes(query.toLowerCase()));
 return <><div className="section-intro"><div><h2>Detection feed <span className="pill">{alerts.length} retained</span></h2><p>Evidence-backed suspicions. Graph warnings link to these exact records.</p></div><a className="button secondary" href="/api/alerts/export"><Download size={17}/>Export stored alerts</a></div><section className="panel"><div className="table-toolbar"><label className="search"><Search size={18}/><input aria-label="Filter detections" placeholder="Search IP, threat class or alert ID" value={query} onChange={e=>setQuery(e.target.value)}/></label><span className="muted">Current session · latest 100 alerts</span></div><div className="table-scroll"><table><thead><tr><th>Threat / record</th><th>Source → destination</th><th>Severity</th><th>Model score</th><th>Observed</th><th>Inspect</th></tr></thead><tbody>{rows.map(a=><tr key={a.id}><td><button className="cell-link" onClick={()=>open(a)}>{pretty(a.threat_class)}</button><small className="mono">{a.id.slice(0,8)} · {a.source}</small></td><td><span className="mono">{a.src}</span><small className="mono">→ {a.dst}</small></td><td><span className={'severity '+a.severity}>{a.severity}</span></td><td>{a.confidence===null?'Uncalibrated':`${Math.round(a.confidence*100)}%`}<small>{a.confidence===null?'Heuristic / anomaly signal':'Synthetic-model vote'}</small></td><td className="mono">{clock(a.timestamp)}</td><td><div className="row-actions"><button className="icon-button" aria-label={`View evidence ${a.id}`} onClick={()=>open(a)}><Eye size={18}/></button><button className="icon-button" aria-label={`View graph for ${a.src}`} onClick={()=>graph(a)}><Network size={18}/></button></div></td></tr>)}</tbody></table>{!rows.length&&<Empty title="No matching detections" detail="Packet capture continues independently of whether a detection is raised."/>}</div></section></>
}
function App({username,onLogout}:{username:string;onLogout:()=>void}){
 const [theme,setTheme]=useState<Theme>(()=>localStorage.getItem('veil-theme')==='light'?'light':'dark'),[tab,setTab]=useState<Tab>('packets'),[state,setState]=useState<State|null>(null),[connected,setConnected]=useState(false),[alert,setAlert]=useState<Alert|null>(null),[packet,setPacket]=useState<Packet|null>(null),[selectedId,setSelectedId]=useState<string|null>(null),[notice,setNotice]=useState('');
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('veil-theme',theme)},[theme]);
 useEffect(()=>{let ws:WebSocket;let timer:ReturnType<typeof setTimeout>;let stopped=false;setConnected(false);const connect=()=>{ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws?view=${tab}`);ws.onopen=()=>setConnected(true);ws.onmessage=e=>setState(JSON.parse(e.data));ws.onclose=e=>{if(e.code===1008){window.dispatchEvent(new Event('veil-signout'));return}if(!stopped){setConnected(false);timer=setTimeout(connect,1500)}}};connect();return()=>{stopped=true;clearTimeout(timer);ws?.close()}},[tab]);
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setAlert(null);setPacket(null)}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[]);
 const replay=async()=>{try{const r=await api('/api/replay',{method:'POST'});const j=await r.json();setNotice(r.ok?'Synthetic replay is running. It includes several source networks; no packets are sent on a network.':j.detail)}catch{setNotice('Backend connection unavailable')}};
 const goGraph=(a:Alert)=>{setSelectedId(a.related_sources?.[0]??a.src);setAlert(null);setTab('graph')};
 const tabs=[{id:'packets' as Tab,title:'Captured packets',icon:Radio},{id:'detections' as Tab,title:'Detections',icon:Eye},{id:'graph' as Tab,title:'Traffic graph',icon:Network},{id:'system' as Tab,title:'System readiness',icon:Layers}];
 const active=tabs.find(t=>t.id===tab)!;
 return <div className="shell"><aside className="sidebar"><div className="brand"><Shield size={29}/><span>VEIL<small>PASSIVE THREAT INTELLIGENCE</small></span></div><div className="workspace">TEAM BLUELOCK <span>SIH 26145</span></div><nav aria-label="Main navigation">{tabs.map(t=><button key={t.id} className={tab===t.id?'active':''} aria-current={tab===t.id?'page':undefined} onClick={()=>setTab(t.id)}><t.icon size={20}/>{t.title}{t.id==='detections'&&<span className="nav-count">{state?.metrics.alerts??0}</span>}</button>)}</nav><div className="sidebar-note"><Shield size={22}/><h3>Capture a copy.</h3><p>The original packet continues to its server. Analysis runs independently.</p><span className="note-label">NO PROBES · NO INLINE BLOCKING</span></div><div className="sidebar-footer"><span className="status-dot"/> Local analyst console</div></aside>
 <main><header><div className="breadcrumb">Security workspace<ChevronRight size={16}/><strong>{active.title}</strong></div><div className="header-actions"><span className="connection"><span className={'status-dot '+(!connected?'muted-dot':'')}/>{connected?'Connected':'Reconnecting'}</span><button className="theme-button" aria-label={`Switch to ${theme==='dark'?'light':'dark'} mode`} onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={20}/>:<Moon size={20}/>}<span>{theme==='dark'?'Light mode':'Dark mode'}</span></button><button className="button secondary" onClick={onLogout} title={`Signed in as ${username}`}>Sign out</button></div></header>
 <div className="content"><div className="title-row"><div><div className="eyebrow">READ-ONLY NETWORK MONITORING</div><h1>{tab==='packets'?'Live traffic':active.title}</h1><p>{tab==='packets'?'Every observed packet. Any source network.':tab==='graph'?'A compact view of who is communicating.':tab==='detections'?'Understand the evidence behind each suspicion.':'Check actual component and capture readiness.'}</p></div><button className="button primary" onClick={replay} disabled={state?.status.mode==='live'||state?.status.mode==='replay'}><Play size={17}/>Run demo replay</button></div>
 {notice&&<div className="notice" role="status"><span>{state?.status.mode==='replay complete'&&notice.startsWith('Synthetic replay is running')?'Synthetic replay complete. Explore the captured packets, relationships, and evidence.':notice}</span><button className="icon-button" aria-label="Dismiss notice" onClick={()=>setNotice('')}><X size={17}/></button></div>}
 <div className="mode-bar"><span className="mode-label"><span className="status-dot"/>{state?.status.mode??'Connecting'}</span><span>One-way mirrored feed</span><span>All observed IPv4 / IPv6 sources</span><span className="push-right">{state?.capabilities.database??'Connecting'}</span></div>
 {tab==='packets'&&<PacketPage state={state} open={setPacket}/>}
 {tab==='detections'&&<DetectionPage alerts={state?.alerts??[]} open={setAlert} graph={goGraph}/>}
 {tab==='graph'&&<TrafficGraph graph={state?.graph??null} alerts={state?.alerts??[]} theme={theme} selectedId={selectedId} setSelectedId={setSelectedId} openAlert={setAlert}/>}
 {tab==='system'&&<><section className="panel readiness"><h2>Component readiness</h2><p>Installed code, trained models, and verified capture are separate checks.</p>{Object.entries(state?.models??{}).map(([k,v])=><div className="readiness-row" key={k}><b>{pretty(k)}</b><span>{v}</span></div>)}{Object.entries(state?.capabilities??{}).map(([k,v])=><div className="readiness-row" key={k}><b>{pretty(k)}</b><span>{v}</span></div>)}</section><section className="panel readiness"><h2>Streaming health</h2>{['parse_errors','state_drops','late_events','drift_events','processing_p95_ms'].map(k=><div className="readiness-row" key={k}><b>{pretty(k)}</b><span>{state?.metrics[k]??0}</span></div>)}<p>{state?.status.last_error??'No ingest error reported.'}</p><p>Capture before server delivery does not mean analysis finishes before delivery. A connected dashboard is not proof of active packet capture.</p></section></>}
 <footer className="footnote page-footer">VEIL prototype · Mirroring visibility depends on the capture point. Synthetic model scores are not real-world accuracy.</footer></div></main>
 {(alert||packet)&&<div className="overlay" onClick={()=>{setAlert(null);setPacket(null)}}><section className="drawer" role="dialog" aria-modal="true" aria-label={alert?'Alert evidence':'Packet details'} onClick={e=>e.stopPropagation()}><button className="close icon-button" aria-label="Close details" onClick={()=>{setAlert(null);setPacket(null)}}><X size={22}/></button>{alert?<><div className="eyebrow">DETECTION RECORD · {alert.id.slice(0,8)}</div><h2>{pretty(alert.threat_class)}</h2><p className="mono">{alert.src} → {alert.dst}</p><span className={'severity '+alert.severity}>{alert.severity}</span><button className="button secondary graph-link" onClick={()=>goGraph(alert)}><Network size={17}/>Locate in graph</button><h3>Why it was flagged</h3>{alert.evidence.map(e=><p className="evidence" key={e}>{e}</p>)}<ShapPanel alert={alert}/><details className="feature-details"><summary>All observed features</summary>{Object.entries(alert.features).map(([k,v])=><div className="feature" key={k}><span>{pretty(k)}</span><b>{Number(v).toFixed(3)}</b></div>)}</details><h3>Evidence limits</h3><p>{alert.confidence_type}. Reverse bytes and outbound/inbound ratio are unavailable. No decrypted content is used.</p></>:packet&&<><div className="eyebrow">CAPTURED PACKET #{packet.sequence}</div><h2>Packet information</h2><div className="packet-path"><span className="mono">{packet.src}:{packet.sport}</span><ArrowRight size={18}/><span className="mono">{packet.dst}:{packet.dport}</span></div><dl className="details-list">{Object.entries({Observed:clock(packet.timestamp,true),Protocol:packet.protocol.toUpperCase(),Size:bytes(packet.length),'Source scope':scopeName(packet.scope),'Address prefix':packet.prefix,'IP version':packet.ip_version,'TCP flags':packet.tcp_flags??'Not available','Zeek flow UID':packet.uid,Input:packet.source}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{String(v)}</dd></div>)}</dl><p>These are observed headers and metadata. Payload content is not shown or decrypted.</p></>}</section></div>}
 </div>
}
function AuthGate(){
 const [user,setUser]=useState<string|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const check=async()=>{try{const r=await fetch('/api/auth/me');if(r.ok){const j=await r.json();csrf=j.csrf;setUser(j.username)}else if(r.status===401){csrf='';setUser(null)}}finally{setLoading(false)}};
 useEffect(()=>{void check().catch(()=>setError('Backend unavailable. Check that VEIL is running.'));const expired=()=>{csrf='';setUser(null)};window.addEventListener('veil-signout',expired);const timer=setInterval(()=>{void check().catch(()=>{})},60000);return()=>{window.removeEventListener('veil-signout',expired);clearInterval(timer)}},[]);
 const logout=async()=>{try{const r=await api('/api/auth/logout',{method:'POST'});if(r.ok||r.status===401){csrf='';setUser(null)}else window.alert('Sign out failed. Please retry.')}catch{window.alert('Backend unavailable. Please retry sign out.')}};
 if(loading)return <div className="login-shell"><p>Opening analyst console…</p></div>;
 if(user)return <App username={user} onLogout={()=>void logout()}/>;
 return <div className="login-shell"><section className="login-card"><SecurityIllustration/><div className="eyebrow">VEIL · ANALYST ACCESS</div><h1>Sign in securely</h1><p>Your passive network intelligence workspace.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const form=e.currentTarget;const fields=new FormData(form);try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:fields.get('username'),password:fields.get('password')})});const j=await r.json();if(r.ok){csrf=j.csrf;form.reset();setUser(j.username)}else setError(typeof j.detail==='string'?j.detail:'Unable to sign in. Check your credentials.')}catch{setError('Backend unavailable. Check that VEIL is running.')}finally{setBusy(false)}}}><label>Username<input name="username" autoComplete="username" required maxLength={64}/></label><label>Password<input name="password" type="password" autoComplete="current-password" required maxLength={128}/></label>{error&&<p role="alert" className="danger-text">{error}</p>}<button className="button primary" disabled={busy}>{busy?'Verifying…':'Sign in to VEIL'}<ArrowRight size={18}/></button></form><p className="footnote">Operator accounts are created locally by your administrator. There is no default password.</p></section></div>
}
createRoot(document.getElementById('root')!).render(<AuthGate/>);
