import {memo,useEffect,useMemo,useRef,useState} from 'react';
import {ReactFlow,Background,Controls,Handle,Position,MarkerType,type Node,type Edge as FlowEdge} from '@xyflow/react';
import {Activity,ChevronLeft,ChevronRight,Focus,Network,Pause,Play,Search,ArrowUpRight,ArrowLeft,Shield,Radio} from 'lucide-react';
import {GNNPanel} from './GNNPanel';
import type {Alert,Host,Edge,Graph,Theme,GNNNode} from './main';
const number=(n:number)=>n.toLocaleString();
const size=(n:number)=>n>=1e6?`${(n/1e6).toFixed(1)} MB`:n>=1000?`${(n/1000).toFixed(1)} kB`:`${n} B`;
const title=(s:string)=>s.replaceAll('_',' ');
const GROUP_PAGE=12,PEER_PAGE=24,DOTS=96;
type Cluster={prefix:string;members:Host[];alertIds:Set<string>;packets:number;bytes:number;internal:number};
const ClusterNode=memo(function ClusterNode({data}:{data:{cluster:Cluster;selected:string|null;select:(id:string)=>void;gnn?:Record<string,GNNNode>}}){
 const {cluster:c,selected,select}=data;const sample=[...c.members.filter(h=>h.alert_ids.length),...c.members.filter(h=>!h.alert_ids.length)].slice(0,DOTS);const radius=65;const hasAlert=c.alertIds.size>0;
 return <div className={`traffic-cluster ${hasAlert?'cluster-alert':''} ${selected==='network:'+c.prefix?'cluster-selected':''}`}>
  <Handle type="target" position={Position.Left}/><Handle type="source" position={Position.Right}/>
  <svg viewBox="0 0 180 166" role="group" aria-label={`${c.prefix}: ${c.members.length} IP addresses`}>
   <circle cx="90" cy="83" r="77" className="cluster-boundary"/>
   {sample.map((h,i)=>{const angle=i*2.399963229728653,r=sample.length===1?0:radius*Math.sqrt((i+.5)/sample.length),x=90+Math.cos(angle)*r,y=83+Math.sin(angle)*r;return <circle key={h.id} cx={x} cy={y} r={selected===h.id?5:3.6} className={`cluster-ip ${h.alert_ids.length?'ip-alert':h.roles.includes('destination')?'ip-destination':'ip-source'} ${h.id===selected?'ip-selected':''} ${data.gnn?.[h.id]?.flagged?'gnn-flagged':''}`} tabIndex={0} role="button" aria-label={`Inspect IP ${h.id}`} onClick={e=>{e.stopPropagation();select(h.id)}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();select(h.id)}}}><title>{h.id} · {h.alert_ids.length} linked detections</title></circle>})}
  </svg>
  <strong>{c.prefix}</strong><span>{number(c.members.length)} IPs · {number(c.alertIds.size)} alerts</span>
  {c.members.length>DOTS&&<small>{DOTS} dots shown · search every IP</small>}
 </div>
});
const IPNode=memo(function IPNode({data}:{data:{host:Host;selected:boolean;gnn?:GNNNode}}){const h=data.host;return <div className={`connection-ip ${h.alert_ids.length?'ip-alert':h.roles.includes('destination')?'ip-destination':'ip-source'} ${data.selected?'connection-selected':''} ${data.gnn?.flagged?'gnn-pattern-node':''}`}><Handle type="target" position={Position.Left}/><i/><Handle type="source" position={Position.Right}/><strong>{h.id}</strong><small>{h.roles.join(' / ')}</small></div>});
const nodeTypes={cluster:ClusterNode,connection:IPNode};

export function TrafficGraph({graph,alerts,theme,selectedId,setSelectedId,openAlert}:{graph:Graph|null;alerts:Alert[];theme:Theme;selectedId:string|null;setSelectedId:(id:string|null)=>void;openAlert:(alert:Alert)=>void}){
 const [query,setQuery]=useState(''),[message,setMessage]=useState(''),[mode,setMode]=useState<'clusters'|'connections'>('clusters'),[page,setPage]=useState(0),[peerPage,setPeerPage]=useState(0),[motion,setMotion]=useState(()=>!window.matchMedia('(prefers-reduced-motion: reduce)').matches),[onlyAlerts,setOnlyAlerts]=useState(false);
 const instance=useRef<{fitView:(o?:{padding?:number;maxZoom?:number;duration?:number})=>Promise<boolean>}|null>(null),fitKey=useRef('');
 const hostMap=useMemo(()=>new Map(graph?.nodes.map(n=>[n.id,n])??[]),[graph]);
 const clusters=useMemo(()=>{const result=new Map<string,Cluster>();for(const h of graph?.nodes??[]){let c=result.get(h.prefix);if(!c){c={prefix:h.prefix,members:[],alertIds:new Set(),packets:0,bytes:0,internal:0};result.set(h.prefix,c)}c.members.push(h);h.alert_ids.forEach(id=>c!.alertIds.add(id))}for(const e of graph?.edges??[]){const c=result.get(hostMap.get(e.source)?.prefix??'');if(c){c.packets+=e.packets;c.bytes+=e.bytes;if(hostMap.get(e.target)?.prefix===c.prefix)c.internal++}}for(const c of result.values())c.members.sort((a,b)=>a.id.localeCompare(b.id));return [...result.values()].sort((a,b)=>a.prefix.localeCompare(b.prefix))},[graph,hostMap]);
 const visibleClusters=clusters.filter(c=>!onlyAlerts||c.alertIds.size);
 const pages=Math.max(1,Math.ceil(visibleClusters.length/GROUP_PAGE)),currentPage=Math.min(page,pages-1);
 const host=selectedId?hostMap.get(selectedId):undefined;
 const group=clusters.find(c=>'network:'+c.prefix===selectedId);
 const focusEdges=useMemo(()=>(graph?.edges??[]).filter(e=>host&&(e.source===host.id||e.target===host.id)&&(!onlyAlerts||e.alert_ids.length)).sort((a,b)=>Number(b.suspicious)-Number(a.suspicious)||b.packets-a.packets||a.id.localeCompare(b.id)),[graph,host,onlyAlerts]);
 const peerIds=[...new Set(focusEdges.map(e=>e.source===host?.id?e.target:e.source))];
 const peerPages=Math.max(1,Math.ceil(peerIds.length/PEER_PAGE)),currentPeerPage=Math.min(peerPage,peerPages-1);
 const selectedPeers=new Set(peerIds.slice(currentPeerPage*PEER_PAGE,(currentPeerPage+1)*PEER_PAGE));
 const showHost=(id:string,connections=false)=>{setSelectedId(id);setPeerPage(0);if(connections)setMode('connections')};
 const focusAlertIds=host?.alert_ids??[...(group?.alertIds??[])];
 const linkedAlerts=alerts.filter(a=>focusAlertIds.includes(a.id));
 const groupMemberIds=useMemo(()=>new Set(group?.members.map(h=>h.id)??[]),[group]);
 const groupTargets=useMemo(()=>{const targets=new Map<string,{sources:Set<string>;packets:number}>();for(const e of graph?.edges??[]){if(!groupMemberIds.has(e.source))continue;const t=targets.get(e.target)??{sources:new Set(),packets:0};t.sources.add(e.source);t.packets+=e.packets;targets.set(e.target,t)}return [...targets].sort((a,b)=>b[1].sources.size-a[1].sources.size||b[1].packets-a[1].packets)},[graph,groupMemberIds]);
 const model=useMemo(()=>{
  const nodes:Node[]=[],edges:FlowEdge[]=[];
  const decorate=(e:{id:string;source:string;target:string;packets:number;recent:boolean;suspicious:boolean},label?:string):FlowEdge=>({id:e.id,source:e.source,target:e.target,type:'default',animated:motion&&e.recent,className:e.recent?'observed-edge':'historical-edge',label,markerEnd:{type:MarkerType.ArrowClosed,color:e.suspicious?'var(--red)':'var(--blue)',width:14,height:14},style:{stroke:e.suspicious?'var(--red)':'var(--blue)',strokeWidth:Math.min(3,1+Math.log10(1+e.packets)*.35),opacity:e.suspicious?.85:.45,strokeDasharray:!e.recent?'3 6':undefined},labelStyle:{fill:'var(--text)',fontSize:14},labelBgStyle:{fill:'var(--panel)',fillOpacity:.94},labelBgPadding:[8,5],selectable:false});
  if(mode==='connections'&&host){
   const peers=[...selectedPeers].map(id=>hostMap.get(id)).filter((h):h is Host=>!!h);
   const rows=Math.max(1,peers.length<=6?peers.length:Math.ceil(peers.length/2));nodes.push({id:host.id,type:'connection',position:{x:20,y:45+(rows-1)*140/2},data:{host,selected:true,gnn:graph?.gnn?.nodes[host.id]},ariaLabel:`IP address ${host.id}`,draggable:false});
   peers.forEach((h,i)=>nodes.push({id:h.id,type:'connection',position:{x:peers.length<=6?470:470+(i%2)*370,y:peers.length<=6?45+i*140:45+Math.floor(i/2)*140+(i%2)*50},data:{host:h,selected:false,gnn:graph?.gnn?.nodes[h.id]},ariaLabel:`IP address ${h.id}`,draggable:false}));
   const chosen=focusEdges.filter(e=>selectedPeers.has(e.source===host.id?e.target:e.source));
   for(const e of chosen){const ports=(e.ports??[]).slice(0,1).map(p=>`${p.protocol.toUpperCase()}/${p.port}`).join('')+((e.ports?.length??0)>1?` +${e.ports!.length-1} ports`:'');edges.push(decorate(e,ports||'Port metadata unavailable'))}
   return {nodes,edges,hidden:focusEdges.length-chosen.length,totalLinks:focusEdges.length,internal:0};
  }
  const batch=visibleClusters.slice(currentPage*GROUP_PAGE,(currentPage+1)*GROUP_PAGE);const shown=new Set(batch.map(c=>c.prefix));
  const aggregated=new Map<string,{id:string;source:string;target:string;packets:number;recent:boolean;suspicious:boolean;relationships:number}>();let internal=0;
  for(const e of graph?.edges??[]){if(onlyAlerts&&!e.suspicious)continue;const s=hostMap.get(e.source)?.prefix,t=hostMap.get(e.target)?.prefix;if(!s||!t)continue;if(s===t){if(shown.has(s))internal++;continue}if(!shown.has(s)||!shown.has(t))continue;const id=s+'|'+t,old=aggregated.get(id)??{id,source:'network:'+s,target:'network:'+t,packets:0,recent:false,suspicious:false,relationships:0};old.packets+=e.packets;old.recent||=e.recent;old.suspicious||=e.suspicious;old.relationships++;aggregated.set(id,old)}
  const columns=Math.max(1,Math.ceil(Math.sqrt(batch.length)));
  batch.forEach((c,i)=>nodes.push({id:'network:'+c.prefix,type:'cluster',position:{x:45+(i%columns)*260+(Math.floor(i/columns)%2)*35,y:30+Math.floor(i/columns)*275},data:{cluster:c,selected:selectedId,select:(id:string)=>showHost(id),gnn:graph?.gnn?.nodes},ariaLabel:`Network ${c.prefix}`,draggable:false}));
  const ordered=[...aggregated.values()].sort((a,b)=>Number(b.suspicious)-Number(a.suspicious)||b.packets-a.packets);const candidates=group?ordered.filter(e=>e.source==='network:'+group.prefix||e.target==='network:'+group.prefix):ordered;
  for(const e of candidates.slice(0,40))edges.push(decorate(e));
  return {nodes,edges,hidden:Math.max(0,candidates.length-40),totalLinks:ordered.length,internal};
 },[graph,clusters,mode,host,selectedId,motion,onlyAlerts,currentPage,currentPeerPage]);
 const layoutKey=mode+':'+currentPage+':'+(mode==='connections'?host?.id+':'+currentPeerPage:'')+':'+!!model.nodes.length;
 useEffect(()=>{if(!model.nodes.length||layoutKey===fitKey.current)return;const timer=setTimeout(()=>{instance.current?.fitView({padding:.18,maxZoom:1.15,duration:motion?350:0});fitKey.current=layoutKey},100);return()=>clearTimeout(timer)},[layoutKey,model.nodes.length,motion]);
 useEffect(()=>{if(mode==='connections'&&!host)setMode('clusters')},[mode,host]);
 const find=()=>{const q=query.trim().toLowerCase();if(!q)return;const h=graph?.nodes.find(n=>n.id.toLowerCase()===q)??graph?.nodes.find(n=>n.id.toLowerCase().includes(q));if(h){setOnlyAlerts(false);showHost(h.id,true);setMessage('');return}const c=clusters.find(c=>c.prefix.toLowerCase().includes(q));if(c){setOnlyAlerts(false);setMode('clusters');setPage(Math.floor(clusters.indexOf(c)/GROUP_PAGE));setSelectedId('network:'+c.prefix);setMessage('');return}setMessage('No matching observed IP or prefix. Search includes all graph pages.')};
 return <>
 <div className="section-intro"><div><h2>Explore traffic relationships</h2><p>See the network in clusters. Follow an IP to its destinations and ports.</p></div><span className="pill lavender">{number(graph?.nodes.length??0)} IPs · {clusters.length} prefixes</span></div>
 <GNNPanel result={graph?.gnn} selectedId={selectedId} select={id=>showHost(id,true)}/>
 <div className="graph-stats"><div><Network size={19}/><span>Observed relationships<strong>{number(graph?.edges.length??0)}</strong></span></div><div><Shield size={19}/><span>Linked detections<strong>{graph?.linked_alerts??0}</strong></span></div><div><Activity size={19}/><span>View<strong>{mode==='clusters'?'Network clusters':'IP connections'}</strong></span></div></div>
 <div className="graph-layout"><section className={`panel topology graph-updated ${motion?'motion-on':'motion-off'}`}>
 <div className="table-toolbar"><form className="search" onSubmit={e=>{e.preventDefault();find()}}><Search size={18}/><input aria-label="Find IP in graph" placeholder="Find any IP or network prefix" value={query} onChange={e=>setQuery(e.target.value)}/><button className="text-button">Find</button></form><button className="button secondary" onClick={()=>instance.current?.fitView({padding:.18,maxZoom:1.15,duration:motion?300:0})}><Focus size={17}/>Fit graph</button></div>
 <div className="graph-toolbar"><button className={'button '+(mode==='clusters'?'primary':'secondary')} onClick={()=>{setMode('clusters');setPeerPage(0)}}><Network size={17}/>Clusters</button><button className={'button '+(mode==='connections'?'primary':'secondary')} disabled={!host} onClick={()=>setMode('connections')}><ArrowUpRight size={17}/>IP connections</button><label className="graph-check"><input type="checkbox" checked={onlyAlerts} onChange={e=>{setOnlyAlerts(e.target.checked);setPage(0);setPeerPage(0)}}/>Linked detections only</label><button className="button secondary" aria-pressed={!motion} onClick={()=>setMotion(!motion)}>{motion?<Pause size={16}/>:<Play size={16}/>} {motion?'Pause motion':'Animate'}</button></div>
 {message&&<p className="inline-note" role="status">{message}</p>}
 <div className="graph-canvas">{model.nodes.length?<ReactFlow nodes={model.nodes} edges={model.edges} nodeTypes={nodeTypes} onInit={i=>{instance.current={fitView:o=>i.fitView(o)}}} onNodeClick={(_,n)=>{if(n.type==='cluster')setSelectedId(n.id);else showHost(n.id)}} onPaneClick={()=>{if(mode==='clusters')setSelectedId(null)}} nodesDraggable={false} nodesConnectable={false} onlyRenderVisibleElements fitView fitViewOptions={{maxZoom:1.15,padding:.18}} minZoom={.08} maxZoom={3} colorMode={theme}><Background color="var(--grid)" bgColor="var(--canvas)" gap={24}/><Controls showInteractive={false}/></ReactFlow>:<div className="empty"><Radio size={28}/><h3>{onlyAlerts?'No matching network clusters':'Waiting for observed traffic'}</h3><p>{onlyAlerts?'Clear the detection filter to see every observed network.':'Start the replay or connect the mirrored metadata stream.'}</p></div>}</div>
 <div className="graph-context"><span>{mode==='clusters'?`${Math.min(GROUP_PAGE,Math.max(0,visibleClusters.length-currentPage*GROUP_PAGE))} of ${visibleClusters.length} prefixes · ${model.edges.length} bundled connections`:`${selectedPeers.size} of ${peerIds.length} peers · ports label each connection`}</span><div><button className="icon-button" aria-label="Previous graph page" disabled={mode==='clusters'?currentPage===0:currentPeerPage===0} onClick={()=>mode==='clusters'?setPage(currentPage-1):setPeerPage(currentPeerPage-1)}><ChevronLeft size={19}/></button><span>{mode==='clusters'?currentPage+1:currentPeerPage+1} / {mode==='clusters'?pages:peerPages}</span><button className="icon-button" aria-label="Next graph page" disabled={mode==='clusters'?currentPage+1>=pages:currentPeerPage+1>=peerPages} onClick={()=>mode==='clusters'?setPage(currentPage+1):setPeerPage(currentPeerPage+1)}><ChevronRight size={19}/></button></div></div>
 <div className="legend"><span><i className="blue"/>Source</span><span><i className="lavender-dot"/>Destination</span><span><i className="red"/>Detection linked</span><span><i className="gnn-legend"/>GNN review ring</span><span>Arrows = observed direction</span><span>Dashed, still = historical</span></div>
 </section><section className="panel node-details graph-inspector" aria-label="Selected node details">
 {host?<><span className="eyebrow">SELECTED IP</span><h3 className="address-title">{host.id}</h3><div className="tag-row"><span className="pill">IPv{host.ip_version}</span><span className="pill">{host.roles.join(' / ')}</span></div><button className="button primary inspect-connections" onClick={()=>setMode('connections')}>Explore connections<ArrowUpRight size={17}/></button><dl className="details-list"><div><dt>Network prefix</dt><dd>{host.prefix}</dd></div><div><dt>Observed packets*</dt><dd>{number(host.packets)}</dd></div><div><dt>Observed bytes*</dt><dd>{size(host.bytes)}</dd></div><div><dt>Peers</dt><dd>{host.peers.length}</dd></div><div><dt>Linked detections</dt><dd>{host.alert_ids.length}</dd></div></dl><h4>Connected IPs</h4><div className="peer-list">{host.peers.map(id=><button className="peer" key={id} onClick={()=>showHost(id,true)}><span className="mono">{id}</span><ChevronRight size={16}/></button>)}</div><h4>Observed destination ports</h4><div className="port-list">{focusEdges.slice(0,24).map(e=><div key={e.id}><strong>{e.source} → {e.target}</strong><span>{e.ports?.length?e.ports.map(p=>`${p.protocol.toUpperCase()}/${p.port} (${number(p.packets)})`).join(' · '):'Not available in retained metadata'}{e.ports_truncated?' · More ports omitted by capture metadata limit':''}</span></div>)}</div></>:group?<><span className="eyebrow">SELECTED NETWORK PREFIX</span><h3 className="address-title">{group.prefix}</h3><p>{number(group.members.length)} IPs · {group.alertIds.size} linked detections</p><dl className="details-list"><div><dt>Source packets*</dt><dd>{number(group.packets)}</dd></div><div><dt>Source bytes*</dt><dd>{size(group.bytes)}</dd></div><div><dt>Internal relationships</dt><dd>{group.internal}</dd></div></dl><h4>Member IP addresses</h4><div className="peer-list">{group.members.map(h=><button className="peer" key={h.id} onClick={()=>showHost(h.id,true)}><span className="mono">{h.id}</span><span className={h.alert_ids.length?'danger-text':''}>{h.alert_ids.length?`${h.alert_ids.length} alerts`:'Inspect'}</span></button>)}</div><h4>Shared destinations</h4><div className="peer-list">{groupTargets.map(([id,t])=><button className="peer" key={id} onClick={()=>showHost(id,true)}><span className="mono">{id}</span><span>{t.sources.size} sources</span></button>)}</div></>:<div className="node-placeholder"><Network size={32}/><h3>Start with a cluster</h3><p>Select a network to see its members. Select any small IP circle, then explore its connections.</p><div className="inspector-step"><span>1</span>Compare network clusters</div><div className="inspector-step"><span>2</span>Follow a source to its ports</div><div className="inspector-step"><span>3</span>Inspect linked evidence</div><p className="footnote">Blue means no retained detection is linked. It does not certify safety.</p></div>}
 {(host||group)&&<><h4>Matching detection records</h4>{linkedAlerts.length?linkedAlerts.map(a=><button className="linked-alert" key={a.id} onClick={()=>openAlert(a)}><span>{title(a.threat_class)}<small>{a.id.slice(0,8)} · {a.severity}</small></span><ArrowUpRight size={17}/></button>):<p>No retained detection linked to this selection.</p>}<p className="footnote">*Totals cover retained relationships, not a fixed-window rate. Prefixes describe address similarity, not ownership.</p></>}
 </section></div>
 <p className="footnote">Motion illustrates direction on recent relationships; moving dashes do not represent individual packets. Cluster links bundle IP relationships; internal links appear in IP connections. Up to {DOTS} real IP dots per cluster, {GROUP_PAGE} prefixes per page, and 40 bundled links are drawn. Search and member lists include every retained IP.{model.hidden>0?` ${model.hidden} additional links are outside this view.`:''}</p>
 {!!graph?.capacity_drops&&<div className="notice">Topology capacity: {number(graph.capacity_drops)} updates omitted by the backend.</div>}
 </>
}
